name: Protect minigraph.py File to avoid further change

on:
  push:
    branches:
      - 'master'
      - '202[2-9][0-9][0-9]'
  pull_request:
    branches:
      - 'master'
      - '202[2-9][0-9][0-9]'

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch base branch
        run: |
          git fetch origin ${GITHUB_BASE_REF}

      - name: Check protected file
        run: |
          echo "Starting file check step"
          protected_file='src/sonic-config-engine/minigraph.py'
          base_branch=$(git rev-parse origin/${GITHUB_BASE_REF})
          if git diff --name-only $base_branch | grep -q "^${protected_file}\$"; then
            echo "Error: You are trying to modify ${protected_file}, which is protected."
            exit 1
          else
            echo "No changes detected in ${protected_file}"
          fi

